# Generated by Django 5.2.4 on 2025-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
